### PR TITLE
handle Guzzle ClientException

### LINKED ISSUE #323: unhandled exception in client when server responds with 4xx on the POST request to create a new upload resource
**Describe the bug**
In the case if the server responds with a 4xx to the POST request to create a new resource the client throws a GuzzleException, that is not handled correctly. 

**To Reproduce**
1. use the owncloud ocis server as TUS server: 
1.1. clone https://github.com/owncloud/ocis
1.2. `cd ocis/ocis`
1.3. `make`
1.4. `PROXY_ENABLE_BASIC_AUTH=true bin/ocis server`
2. use this tus-php code to provoke a 401 response
    ```
    $client = new \TusPhp\Tus\Client(
	'https://localhost:9200',
        'verify' => false]
    );

    $key = 'your unique key';
    $client->setApiPath("/remote.php/dav/files/admin");

    $client->setKey($key)->file('/tmp/upload.txt', 'filename.txt');
    $client->file('/tmp/upload.txt', 'filename.txt')->upload();
    ```
     (adding `'headers' => ['Authorization' => 'Basic ' . \base64_encode('admin:admin')]` to the client will make the upload work)
3. run the php-tus code => 
    ```
    PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://localhost:9200/remote.php/dav/files/admin` resulted in a `401 Unauthorized` response in /home/artur/www/tus-bug/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
    Stack trace:
    #0 /home/artur/www/tus-bug/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
    #1 /home/artur/www/tus-bug/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
    #2 /home/artur/www/tus-bug/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
    #3 /home/artur/www/tus-bug/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
    #4 /home/artur/www/tus-bug/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
    #5 /home/artur/www/tus-bug/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
    #6 /home/artur/www/tu in /home/artur/www/tus-bug/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
    ```

**Expected behavior**
the Guzzle exception should be handled and a tus-php exception (TusPhp\Exception\FileException) should be thrown

**Additional context**
The same issue happens when e.g. the destination folder does not exists and the server replies with 404
a try, catch block should be added around https://github.com/ankitpokhrel/tus-php/blob/master/src/Tus/Client.php#L440-L442
I will create a PR

### PR DESCRIPTION
**Pull request by individual-it**
in case of an 4xx error Guzzle throws a ClientException and the response is inside of that

fixes #323

### CODE REVIEW

File: tests/Tus/ClientTest.php [hunk 1]
```diff
@@ -1349,10 +1350,11 @@ public function it_throws_exception_when_unable_to_create_resource() : void
         $checksum     = hash_file('sha256', $filePath);
         $guzzleMock   = m::mock(Client::class);
         $responseMock = m::mock(Response::class);
+        $requestMock  = m::mock(Request::class);
 
         $responseMock
             ->shouldReceive('getStatusCode')
-            ->once()
+            ->twice()
```
Comment (ankitpokhrel) [inline tests/Tus/ClientTest.php:1357]: `getStatusCode` is not expected to be called twice

**Review by ankitpokhrel — COMMENTED** [review]
Hi @individual-it, thank you for reporting the issue and working on a fix. The core changes look ok to me. However, I have some comments on changes related to the test.

The expectation from `getStatusCode` is not changed, so we don't need to touch that part. What we can do here is, mock the guzzle ClientException and add expectations for it.

Something like this would make more sense:
```diff
diff --git a/tests/Tus/ClientTest.php b/tests/Tus/ClientTest.php
index 38e4244..3036405 100644
--- a/tests/Tus/ClientTest.php
+++ b/tests/Tus/ClientTest.php
@@ -2,7 +2,6 @@

 namespace TusPhp\Test\Tus;

-use GuzzleHttp\Psr7\Request;
 use Mockery as m;
 use GuzzleHttp\Client;
 use TusPhp\Cache\FileStore;
@@ -1350,11 +1349,10 @@ class ClientTest extends TestCase
         $checksum     = hash_file('sha256', $filePath);
         $guzzleMock   = m::mock(Client::class);
         $responseMock = m::mock(Response::class);
-        $requestMock  = m::mock(Request::class);

         $responseMock
             ->shouldReceive('getStatusCode')
-            ->twice()
+            ->once()
             ->andReturn(400);

         $this->tusClientMock
@@ -1369,6 +1367,13 @@ class ClientTest extends TestCase

         $this->tusClientMock->file($filePath, $fileName);

+        $clientExceptionMock = m::mock(ClientException::class);
+
+        $clientExceptionMock
+            ->shouldReceive('getResponse')
+            ->once()
+            ->andReturn($responseMock);
+
         $guzzleMock
             ->shouldReceive('post')
             ->once()
@@ -1380,13 +1385,7 @@ class ClientTest extends TestCase
                     'Upload-Metadata' => 'filename ' . base64_encode($fileName),
                 ],
             ])
-            ->andThrow(
-                new ClientException(
-                    'Client error: `POST files` resulted in a `400 Bad Request` response',
-                    $requestMock,
-                    $responseMock
-                )
-            );
+            ->andThrow($clientExceptionMock);

         $this->tusClientMock->create($key);
     }
```

**Comment by individual-it** [comment]
@ankitpokhrel thank you for your review. I've adjusted the tests according to your suggestions

File: tests/Tus/ClientTest.php (hunk 1 above)
Comment (individual-it) [reply tests/Tus/ClientTest.php]: yes, with the mock it only fires once. With my original changes the Guzzle exception accessed this function also, so it got fired twice.
Its fixed now

**Review by ankitpokhrel — APPROVED** [review]

**Comment by ankitpokhrel** [comment]
Thank you @individual-it 🎉

**Comment by individual-it** [comment]
@ankitpokhrel could you trigger a new release, so that I can easily use it with composer?

**Comment by ankitpokhrel** [comment]
@individual-it I will do it in few hours.

**Comment by ankitpokhrel** [comment]
Released [v2.1.1](https://github.com/ankitpokhrel/tus-php/releases/tag/v2.1.1)
